### ISSUE TITLE
请问怎么查我是否运行正常并在抢注？

### ISSUE THREAD

**Issue by CatQuan** [slippersheepig/oracle_arm#1]
![image](https://github.com/user-attachments/assets/8c3713cb-7242-4ef9-9553-d7e0fd2958bd)
电报没有反馈 该填的都填了 我想知道进度 最少知道脚本在正常运作？

**Comment by CatQuan** [comment]
root@VM-8-2-ubuntu:~# docker-compose up -d
Starting oci ... done
root@VM-8-2-ubuntu:~# reboot

**Comment by CatQuan** [comment]
.env 里都接了 一点提示没有

**Comment by CatQuan** [comment]
![image](https://github.com/user-attachments/assets/71ca5883-f1a4-4256-b58d-733b7774095b)
接下来怎么办

**Comment by slippersheepig** [comment]
一旦运行成功，电报会立即收到一条信息“XX正在快马加鞭抢购了”，如果没收到就是有问题。截图里status已经是退出状态了，docker logs oci可以查看日志，看看输出内容

**Comment by CatQuan** [comment]
![image](https://github.com/user-attachments/assets/2b12e8b7-3aad-4e81-adea-72b5c5bba9a5)
感谢老师

**Comment by slippersheepig** [comment]
> ![image](https://private-user-images.githubusercontent.com/116005003/352694344-2b12e8b7-3aad-4e81-adea-72b5c5bba9a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwNTA0MjQsIm5iZiI6MTcyMjA1MDEyNCwicGF0aCI6Ii8xMTYwMDUwMDMvMzUyNjk0MzQ0LTJiMTJlOGI3LTNhYWQtNGU4MS1hZGVhLTcyYjVjNWJiYTlhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyN1QwMzE1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTIzMjc5MmZlNDRkYjU2ZWViNzFiODBlODZkYWZkMmE4YmM4ZmMxODdmYzhkZTczMmIwNzExNGUxYzY4MTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q6bKb5jZFZ81ck7L5eCnB2ic4eFLgU-C1qVSszewaAY) 感谢老师

缺少key文件

**Comment by CatQuan** [comment]
![image](https://github.com/user-attachments/assets/59618e73-8d41-4b10-b24a-5ee2a259546e)
前面问题已解决 新问题来了
（前面是因为漏了key_file指定私钥文件，所以私钥报无）

**Comment by CatQuan** [comment]
![image](https://github.com/user-attachments/assets/1e9ed109-1ae9-4705-92b9-ad7116faa05c)
不应该返回500错误吗？500是容量不足。

**Comment by CatQuan** [comment]
求助，请问是脚本问题，还是我配置问题？

**Comment by slippersheepig** [comment]
> 求助，请问是脚本问题，还是我配置问题？

脚本没问题，你需要按提示查看甲骨文的文档解决，Invalid DNS label 2大概是网络标签相关问题

**Comment by CatQuan** [comment]
我换了两台不同的VPS供应商 都是同样的错误
